topics:
  - music-downloader
  - spotify-api
  - python
  - youtube-dl
  - music-player
  - spotify
  - python3
  - desktop-application
  - cross-platform
  - gui-application
  - pyqt
  - music-library
  - audio-player
  - multimedia
  - spotify-client
