[build]
  command = "pip install mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin && python -m mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 