[build]
  command = "pip install 'mkdocs-material>=9.0.0' mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin pillow && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"