name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel

    - name: Build package
      run: |
        python -m build
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Motify ${{ github.ref }} Release
          
          ### What's New
          - Initial release of Motify
          - Music download functionality
          - Spotify integration
          - YouTube support
          - Custom themes
          - Download queue management
          
          ### Installation
          ```bash
          pip install motify
          ```
          
          For detailed installation instructions, visit our [documentation](https://mosh3eb.github.io/motify/).
        draft: false
        prerelease: false
        
    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/motify-1.0.0.tar.gz
        asset_name: motify-1.0.0.tar.gz
        asset_content_type: application/gzip
